# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  python-docker:
    docker:
      - image: circleci/python:3.8
jobs:
  get_poetry:  # maybe abusing the build step here, this just gets poetry
    executor: python-docker
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install --no-install-recommends -y build-essential
      - run: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  test:
    executor: python-docker
    steps:
      - attach_workspace:
          at: .
      - run: poetry run pytest --no-header --new-first --showlocals
  # publish_test_pypi:
  #   executor: python-docker
  #     - attach_workspace:
  #         at: .
  #     - run: poetry publish --build -r test-pypi
  #   steps: 
workflows:
  build_test:
    jobs:
      - get_poetry
      - test:
          requires:
            - get_poetry
