version: 2.1
executors:
  python-docker:
    docker:
      - image: circleci/python:3.8
jobs:
  get_poetry:
    executor: python-docker
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install --no-install-recommends -y build-essential
      - run: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python - --version 1.1.0rc1
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor: python-docker
    steps:
      - attach_workspace:
          at: .
      - run: poetry install
      - run: poetry run pytest --new-first --showlocals
  publish_test_pypi:
    executor: python-docker
    steps:
      - attach_workspace:
          at: .
      - run: poetry config repositories.test-pypi "https://test.pypi.org/legacy/"
      # there's a dupe of this env var
      - run: poetry config pypi-token.test-pypi "${PYPI_TEST_TOKEN}"
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run: poetry publish --build -r test-pypi
  publish_pypi:
    executor: python-docker
    steps:
      - attach_workspace:
          at: .
      - run: poetry config repositories.pypi "https://pypi.org/legacy/"
      # there's a dupe of this env var
      - run: poetry config pypi-token.test-pypi "${PYPI_TOKEN}"
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run: poetry publish --build
workflows:
  build_test:
    jobs:
      - get_poetry
      - test:
          requires:
            - get_poetry
  build_publish_test_pypi:
    when:
      equal: [ pypi-test, << pipeline.git.branch >> ]
    jobs:
      - get_poetry
      - test:
          requires:
            - get_poetry
      - publish_test_pypi:
          requires:
            - get_poetry
            - test
          context:
            - pypi
