# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  python-docker:
    docker:
      - image: circleci/python:3.8
jobs:
  get_poetry:  # maybe abusing the build step here, this just gets poetry
    executor: python-docker
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install --no-install-recommends -y build-essential
      - run: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor: python-docker
    steps:
      - attach_workspace:
          at: .
      - run: poetry install
      - run: poetry run pytest --new-first --showlocals
  publish_test_pypi:
    executor: python-docker
    steps:
      - attach_workspace:
          at: .
      - run: poetry config repositories.test-pypi "https://test.pypi.org/legacy/"
      - run: poetry config pypi-token.test-pypi ${PYPI_TEST_TOKEN}
      - run: poetry publish --build -r test-pypi
workflows:
  build_test:
    jobs:
      - get_poetry
      - test:
          requires:
            - get_poetry
  build_publish_test_pypi:
    jobs:
      - get_poetry
      - publish_test_pypi:
          requires:
            - get_poetry
